In [1]:
import torch.nn as nn
import torch

### 1.conv
torch.nn.Conv2d(in_channels, # 参数代表输入特征矩阵的深度即channel，比如输入一张RGB彩色图像，那in_channels=3  
           out_channels, # 参数代表卷积核的个数，使用n个卷积核输出的特征矩阵深度即channel就是n  
           kernel_size,             
           stride=1,            
           padding=0,  # padding双向 计算时为2p             
           dilation=1,             
           groups=1,             
           bias=True,             
           padding_mode='zeros') # 计算时小数忽略掉  
           

In [2]:
im = torch.randn([1, 3, 640, 640])
print(im.shape)

conv = nn.Conv2d(1, 1, kernel_size=6, stride=2, padding=2)
conv.weight.data = torch.randn([32, 3, 6, 6])
conv.bias.data = torch.randn(32)

output = conv(im)
print(output.shape)

torch.Size([1, 3, 640, 640])
torch.Size([1, 32, 320, 320])


###  2.mul
tensor乘法，对应位置相乘，输出shape大小取决于shape最大的

In [12]:
# tensor乘法，对应位置相乘，输出shape大小取决于shape最大的
c = torch.tensor([[1, 2], [3, 4]])
d = torch.tensor([[2, 3], [2, 3]])
print(c[0][0])
print(c*d)
print((c*d).shape)

tensor(1)
tensor([[ 2,  6],
        [ 6, 12]])
torch.Size([2, 2])


### 3.sigmiod


In [13]:
sigmoid = nn.Sigmoid()
out = sigmoid(output)
print(out.shape)
out = output * sigmoid(output)

torch.Size([1, 32, 320, 320])


### 4.concat
-1:最后一行拼接

In [16]:
a = torch.randn([1,3,3,3])
b = torch.randn([1,3,3,3])
concat1 = torch.cat((a, b), 1)
concat2 = torch.cat((a, b), -1)
concat1.shape, concat2.shape,concat1,concat2

(torch.Size([1, 6, 3, 3]),
 torch.Size([1, 3, 3, 6]),
 tensor([[[[ 0.4016,  0.0119,  0.6903],
           [ 0.4645,  0.7372, -0.3828],
           [ 0.5392, -0.7477,  0.6270]],
 
          [[-2.4104,  1.5953,  1.3159],
           [ 0.1681,  0.4798, -0.5721],
           [ 0.3801, -1.0804, -0.1560]],
 
          [[ 0.0092, -0.0570, -2.1333],
           [-1.2557, -1.2996, -0.9345],
           [ 0.4598,  1.2953, -0.3510]],
 
          [[-0.2296,  0.6702, -1.2109],
           [ 0.9283, -0.0712,  1.4104],
           [ 0.5527, -0.1876, -0.9190]],
 
          [[-2.1579, -0.8180, -1.3417],
           [ 0.1302,  1.1660, -0.8441],
           [-0.9415,  0.9346,  1.3974]],
 
          [[ 0.0852, -0.9057,  2.7632],
           [ 3.6334, -1.0795, -0.4441],
           [-0.5153, -0.1799, -0.3969]]]]),
 tensor([[[[ 0.4016,  0.0119,  0.6903, -0.2296,  0.6702, -1.2109],
           [ 0.4645,  0.7372, -0.3828,  0.9283, -0.0712,  1.4104],
           [ 0.5392, -0.7477,  0.6270,  0.5527, -0.1876, -0.9190]],
 
   

### 5.reshape

In [18]:
e = torch.randn([1,3,3,3])
e_reshape = e.reshape([3,3,3,1])
e.shape,e_reshape,e

(torch.Size([1, 3, 3, 3]),
 tensor([[[[ 0.0665],
           [ 0.1563],
           [ 0.9765]],
 
          [[ 0.7202],
           [ 1.3021],
           [-0.8556]],
 
          [[-0.3020],
           [-0.4009],
           [ 1.1986]]],
 
 
         [[[-1.3320],
           [-0.7188],
           [-1.5247]],
 
          [[-1.0172],
           [-0.4447],
           [-0.3046]],
 
          [[-2.6674],
           [ 0.5087],
           [ 1.2057]]],
 
 
         [[[-0.8944],
           [-1.2396],
           [ 0.3444]],
 
          [[ 1.0384],
           [-1.5023],
           [-0.9823]],
 
          [[-1.5396],
           [-0.4714],
           [-1.0320]]]]),
 tensor([[[[ 0.0665,  0.1563,  0.9765],
           [ 0.7202,  1.3021, -0.8556],
           [-0.3020, -0.4009,  1.1986]],
 
          [[-1.3320, -0.7188, -1.5247],
           [-1.0172, -0.4447, -0.3046],
           [-2.6674,  0.5087,  1.2057]],
 
          [[-0.8944, -1.2396,  0.3444],
           [ 1.0384, -1.5023, -0.9823],
           [-1.5396

### 6.maxpool
non-empty 3D or 4D (batch mode) tensor expected for input
输入至少是3维tensor

In [35]:
maxpool = nn.MaxPool2d(kernel_size=2,stride=1,padding=0)
# f = torch.randn([2, 3, 3, 3])
f = torch.arange(9, dtype=torch.float).reshape([1, 1, 3, 3])
f_out = maxpool(f)
f,f.shape,f_out,f_out.shape

(tensor([[[[0., 1., 2.],
           [3., 4., 5.],
           [6., 7., 8.]]]]),
 torch.Size([1, 1, 3, 3]),
 tensor([[[[4., 5.],
           [7., 8.]]]]),
 torch.Size([1, 1, 2, 2]))

### 7.add sub pow
对应位置作为base和power

In [40]:
g = torch.arange(9, dtype=torch.float).reshape([1, 1, 3, 3])
g_add = g + 2
g_sub = g - 0.5
g_pow = torch.pow(g, 2)
g_add,g_sub,g_pow

(tensor([[[[ 2.,  3.,  4.],
           [ 5.,  6.,  7.],
           [ 8.,  9., 10.]]]]),
 tensor([[[[-0.5000,  0.5000,  1.5000],
           [ 2.5000,  3.5000,  4.5000],
           [ 5.5000,  6.5000,  7.5000]]]]),
 tensor([[[[ 0.,  1.,  4.],
           [ 9., 16., 25.],
           [36., 49., 64.]]]]))

### 8.resize
可能比较难写

In [48]:
from torchvision.transforms import Resize

torch_resize = Resize([4,9]) # 定义Resize类对象
h = torch.arange(6, dtype=torch.float).reshape([1, 1, 2, 3])
h_resize = torch_resize(h)
h,h_resize

(tensor([[[[0., 1., 2.],
           [3., 4., 5.]]]]),
 tensor([[[[0.0000e+00, 1.4901e-08, 3.3333e-01, 6.6667e-01, 1.0000e+00,
            1.3333e+00, 1.6667e+00, 2.0000e+00, 2.0000e+00],
           [7.5000e-01, 7.5000e-01, 1.0833e+00, 1.4167e+00, 1.7500e+00,
            2.0833e+00, 2.4167e+00, 2.7500e+00, 2.7500e+00],
           [2.2500e+00, 2.2500e+00, 2.5833e+00, 2.9167e+00, 3.2500e+00,
            3.5833e+00, 3.9167e+00, 4.2500e+00, 4.2500e+00],
           [3.0000e+00, 3.0000e+00, 3.3333e+00, 3.6667e+00, 4.0000e+00,
            4.3333e+00, 4.6667e+00, 5.0000e+00, 5.0000e+00]]]]))

### 9.transpose
与reshape不同，
多维时用permute,y[c][b][a] = x[a][b][c]

In [43]:
i = torch.arange(6, dtype=torch.float).reshape([1, 2, 3])
i_reshape = i.reshape([ 3, 2, 1])
i_permute = i.permute(2, 1, 0)
i,i_permute,i_permute.shape

(tensor([[[0., 1., 2.],
          [3., 4., 5.]]]),
 tensor([[[0.],
          [3.]],
 
         [[1.],
          [4.]],
 
         [[2.],
          [5.]]]),
 torch.Size([3, 2, 1]))

### 10.slice